[project]
authors = [
    "Alexander CS Hendorf <alexander@pioneershub.org>",
]
channels = ["conda-forge"]
description = "Docs for organizing PyCon DE & Pydata 2025"
name = "conference"
platforms = ["osx-arm64", "win-64", "linux-64", "osx-64", "linux-aarch64"]
version = "0.3.4"

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."

[dependencies]
python = "3.12.*"
pixi-pycharm = ">=0.0.6,<0.0.7"
omegaconf = ">=2.3.0,<2.4"

[pypi-dependencies]
mkdocs-material = { version = ">=9.5.39, <10", extras = ["imaging"] }
mkdocs = ">=1.6.1, <2"
mkdocs-glightbox = ">=0.4.0, <0.5"
bumpversion = ">=0.6.0, <0.7"
pymdown-extensions = ">=10.11.2, <11"
mkdocs-open-in-new-tab = ">=1.0.5, <2"
mkdocs-macros-plugin = ">=1.2.0, <2"
pytanis = "*"
webcolors = "*"

[tool.pixi.dependencies]
ruff = ">=0.4.8,<0.5"

[feature.lint.dependencies]
pre-commit = "*"
[feature.lint.tasks]
lint = "pre-commit run --all"

[environments]
default = ["lint"]
